# Generated by Django 4.1.4 on 2023-01-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=150, verbose_name='название поля')),
                ('branch_name', models.CharField(max_length=150, verbose_name='название ветки')),
                ('nest_name', models.CharField(max_length=150, verbose_name='название вложенности')),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='menu', to='menus.menu')),
            ],
            options={
                'verbose_name': 'Поле меню',
                'verbose_name_plural': 'Поля меню',
            },
        ),
    ]
